### ISSUE TITLE
[ImportError]BaseWebSocket not found

### ISSUE THREAD

**Issue by abrahum** [nonebot/plugin-test#5]
ImportError: cannot import name 'BaseWebSocket' from 'nonebot.drivers'
nonebot.drivers下只有一个fastapi

**Comment by abrahum** [comment]
好像改名成WebSocket了，fastapi里发现成这样了
`from nonebot.drivers import Driver as BaseDriver, WebSocket as BaseWebSocket`

**Comment by abrahum** [comment]
view.py 内line14更改为
`from nonebot.drivers import WebSocket as BaseWebSocket`
解决该问题

**Comment by yanyongyu** [comment]
新版本已适配
