### ISSUE TITLE
聊天窗口支持跨域

### ISSUE THREAD

**Issue by Ledenel** [nonebot/plugin-test#6]
在WSL2上开发时，聊天窗口会遇到跨域问题，由于WSL2的虚拟机具有独立的IP。目前默认禁止了跨域，使test接口无法从IP访问。现在可以通过monkey patch的方式，在插件加载之后暂时解决跨域问题：
```python
import nonebot_plugin_test
nonebot_plugin_test.sio.eio.cors_allowed_origins = "*"
```
希望能够提供out-of-the-box的支持。

**Comment by yanyongyu** [comment]
fixed in master
