### ISSUE TITLE
[feature]希望在前端增加连接到 已连接的其他bot 功能

### ISSUE THREAD

**Issue by abrahum** [nonebot/plugin-test#9]
希望可以增加一个连接到其他bot的功能

选定bot，然后输入群号或qq号创建一个matcher转发该群的消息到test前端
test前端的发送消息由bot转发给该群或qq号

（WebQQ借尸还魂，笑）

**Comment by yanyongyu** [comment]
test前端仅供测试使用，也不会监控或转发其他bot的消息，这个功能不会实现
